language: node_js
node_js:
  - "8.11.2"
cache:
  yarn: true
  directories:
  - node_modules
script:
#- yarn build
#- yarn lint
- yarn deploy --skipPrompts
notifications:
  email: false
  slack: toysmore:vqiigMOfdyuRlEIuJtkuNkby
  template:
     - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
     - "Execution time: *%{duration}*"
     - "Message: %{message}"
