language: node_js
node_js:
  - "8.11.2"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn buildxxx
- yarn lint
notifications:
  email: false
  slack: toysmore:vqiigMOfdyuRlEIuJtkuNkby
  template:
      - "%{repository_slug} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
