language: node_js
node_js:
  - "8.11.2"
cache:
  yarn: true
  directories:
  - node_modules
script:
#- yarn build
#- yarn lint
- yarn deploy --skipPrompts
notifications:
  email: false
  slack: toysmore:vqiigMOfdyuRlEIuJtkuNkby
  template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
